2025-06-23 00:57:32 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:44:04 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:45:35 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:45:49 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:47:12 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:47:12 - login_window - DEBUG - Login UI components created.
2025-06-23 01:47:12 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 01:47:12 - login_window - INFO - LoginWindow initialized.
2025-06-23 01:47:44 - login_window - INFO - Attempting login for user: Manokuz
2025-06-23 01:47:44 - login_window - INFO - User Manokuz logged in successfully.
2025-06-23 01:48:46 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:48:46 - login_window - DEBUG - Login UI components created.
2025-06-23 01:48:46 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 01:48:46 - login_window - INFO - LoginWindow initialized.
2025-06-23 01:48:57 - login_window - WARNING - Failed login attempt for Manokuz: Неверное имя пользователя или пароль.
2025-06-23 01:50:23 - login_window - DEBUG - Logger initialized successfully
2025-06-23 01:50:24 - login_window - DEBUG - Login UI components created.
2025-06-23 01:50:24 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 01:50:24 - login_window - INFO - LoginWindow initialized.
2025-06-23 01:50:33 - login_window - ERROR - An error occurred during login: 'UserModel' object has no attribute 'set_user_data'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 120, in login
    success, message = self.controller.login(username, password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\controllers\auth_controller.py", line 133, in login
    self.user_model.set_user_data(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserModel' object has no attribute 'set_user_data'
2025-06-23 02:00:07 - login_window - ERROR - An error occurred during login: 'UserModel' object has no attribute 'set_user_data'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 120, in login
    success, message = self.controller.login(username, password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\controllers\auth_controller.py", line 133, in login
    self.user_model.set_current_user(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UserModel' object has no attribute 'set_user_data'
2025-06-23 02:01:34 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:01:34 - login_window - DEBUG - Login UI components created.
2025-06-23 02:01:34 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:01:34 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:01:48 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:01:49 - login_window - DEBUG - Login UI components created.
2025-06-23 02:01:49 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:01:49 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:03:46 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:03:58 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:04:13 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:04:13 - login_window - DEBUG - Login UI components created.
2025-06-23 02:04:13 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:04:13 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:04:31 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:06:34 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:06:34 - login_window - DEBUG - Login UI components created.
2025-06-23 02:06:34 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:06:34 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:06:45 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:17:06 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:17:06 - login_window - DEBUG - Login UI components created.
2025-06-23 02:17:06 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:17:06 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:17:16 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:17:16 - login_window - ERROR - An error occurred during login: DashboardWindow.__init__() takes from 2 to 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 126, in login
    self.parent.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DashboardWindow.__init__() takes from 2 to 3 positional arguments but 4 were given
2025-06-23 02:19:32 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:19:33 - login_window - DEBUG - Login UI components created.
2025-06-23 02:19:33 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:19:33 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:19:42 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:19:45 - login_window - ERROR - An error occurred during login: 'DashboardWindow' object has no attribute 'load_styles'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 126, in login
    self.parent.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(self.user_model, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 75, in __init__
    self.load_styles()
    ^^^^^^^^^^^^^^^^
AttributeError: 'DashboardWindow' object has no attribute 'load_styles'
2025-06-23 02:21:28 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:21:29 - login_window - DEBUG - Login UI components created.
2025-06-23 02:21:29 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:21:29 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:21:37 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:21:39 - login_window - ERROR - An error occurred during login: 'DashboardWindow' object has no attribute 'username_label'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 126, in login
    self.parent.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 134, in go_to_dashboard
    self.dashboard_window.update_user(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 83, in update_user
    self.update_profile_info()
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 147, in update_profile_info
    self.username_label.setText(f"Добро пожаловать, {self.username}!")
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DashboardWindow' object has no attribute 'username_label'
2025-06-23 02:25:48 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:25:48 - login_window - DEBUG - Login UI components created.
2025-06-23 02:25:48 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:25:48 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:25:58 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:26:00 - login_window - ERROR - An error occurred during login: 'DashboardWindow' object has no attribute 'username_label'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 126, in login
    self.parent.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 134, in go_to_dashboard
    self.dashboard_window.update_user(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 83, in update_user
    self.update_profile_info()
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 148, in update_profile_info
    self.username_label.setText(f"Добро пожаловать, {self.username}!")
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DashboardWindow' object has no attribute 'username_label'
2025-06-23 02:31:20 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:31:20 - login_window - DEBUG - Login UI components created.
2025-06-23 02:31:20 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:31:20 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:31:28 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:31:30 - login_window - ERROR - An error occurred during login: 'DashboardWindow' object has no attribute 'username_label'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 126, in login
    self.parent.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 134, in go_to_dashboard
    self.dashboard_window.update_user(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 83, in update_user
    self.update_profile_info()
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 148, in update_profile_info
    self.username_label.setText(f"Добро пожаловать, {self.username}!")
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DashboardWindow' object has no attribute 'username_label'
2025-06-23 02:34:26 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:34:27 - login_window - DEBUG - Login UI components created.
2025-06-23 02:34:27 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:34:27 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:34:37 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:46:37 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:46:37 - login_window - DEBUG - Login UI components created.
2025-06-23 02:46:37 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:46:37 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:46:47 - login_window - INFO - User Usr logged in successfully.
2025-06-23 02:50:08 - login_window - DEBUG - Logger initialized successfully
2025-06-23 02:50:08 - login_window - DEBUG - Login UI components created.
2025-06-23 02:50:08 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 02:50:08 - login_window - INFO - LoginWindow initialized.
2025-06-23 02:50:32 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:06:05 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:06:05 - login_window - DEBUG - Login UI components created.
2025-06-23 03:06:05 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:06:05 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:06:12 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:20:10 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:20:11 - login_window - DEBUG - Login UI components created.
2025-06-23 03:20:11 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:20:11 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:20:21 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:17:14 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:17:15 - login_window - DEBUG - Login UI components created.
2025-06-23 03:17:15 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:17:15 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:17:27 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:21:35 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:21:36 - login_window - DEBUG - Login UI components created.
2025-06-23 03:21:36 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:21:36 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:21:47 - login_window - WARNING - Failed login attempt for Usr: Неверное имя пользователя или пароль.
2025-06-23 03:21:55 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:23:00 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:23:01 - login_window - DEBUG - Login UI components created.
2025-06-23 03:23:01 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:23:01 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:24:07 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:24:07 - login_window - DEBUG - Login UI components created.
2025-06-23 03:24:07 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:24:07 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:24:16 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:25:49 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:25:49 - login_window - DEBUG - Login UI components created.
2025-06-23 03:25:49 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:25:49 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:26:15 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:28:59 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:29:00 - login_window - DEBUG - Login UI components created.
2025-06-23 03:29:00 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:29:00 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:29:19 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:30:32 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:30:33 - login_window - DEBUG - Login UI components created.
2025-06-23 03:30:33 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:30:33 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:30:44 - login_window - INFO - User Usr logged in successfully.
2025-06-23 03:32:14 - login_window - DEBUG - Logger initialized successfully
2025-06-23 03:32:14 - login_window - DEBUG - Login UI components created.
2025-06-23 03:32:14 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-23 03:32:14 - login_window - INFO - LoginWindow initialized.
2025-06-23 03:32:23 - login_window - INFO - User Manokuz logged in successfully.
2025-06-23 03:42:34 - login_window - DEBUG - Logger initialized successfully
2025-06-24 12:06:02 - login_window - DEBUG - Logger initialized successfully
2025-06-24 12:06:04 - login_window - DEBUG - Login UI components created.
2025-06-24 12:06:04 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-24 12:06:04 - login_window - INFO - LoginWindow initialized.
2025-06-24 12:11:09 - login_window - DEBUG - Logger initialized successfully
2025-06-24 12:11:10 - login_window - DEBUG - Login UI components created.
2025-06-24 12:11:10 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-24 12:11:10 - login_window - INFO - LoginWindow initialized.
2025-06-24 12:11:21 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 00:40:24 - login_window - DEBUG - Logger initialized successfully
2025-06-25 00:40:25 - login_window - DEBUG - Login UI components created.
2025-06-25 00:40:25 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 00:40:25 - login_window - INFO - LoginWindow initialized.
2025-06-25 00:40:41 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 00:40:42 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 487, in get_scans_by_user
    result_data = decrypt_sensitive_data(row[2])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 00:43:19 - login_window - DEBUG - Logger initialized successfully
2025-06-25 00:43:20 - login_window - DEBUG - Login UI components created.
2025-06-25 00:43:20 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 00:43:20 - login_window - INFO - LoginWindow initialized.
2025-06-25 00:43:27 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 00:43:27 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 497, in get_scans_by_user
    decrypted_url = decrypt_sensitive_data(row[1])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 00:44:11 - login_window - INFO - User User logged in successfully.
2025-06-25 08:23:20 - login_window - DEBUG - Logger initialized successfully
2025-06-25 08:23:21 - login_window - DEBUG - Login UI components created.
2025-06-25 08:23:21 - login_window - WARNING - Файл стилей styles.qss не найден: styles.qss
2025-06-25 08:23:21 - login_window - INFO - LoginWindow initialized.
2025-06-25 08:25:04 - login_window - DEBUG - Logger initialized successfully
2025-06-25 08:25:05 - login_window - DEBUG - Login UI components created.
2025-06-25 08:25:05 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 08:25:05 - login_window - INFO - LoginWindow initialized.
2025-06-25 08:25:21 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 08:25:21 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 497, in get_scans_by_user
    decrypted_url = decrypt_sensitive_data(row[1])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 08:26:04 - login_window - DEBUG - Logger initialized successfully
2025-06-25 08:26:05 - login_window - DEBUG - Login UI components created.
2025-06-25 08:26:05 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 08:26:05 - login_window - INFO - LoginWindow initialized.
2025-06-25 08:26:18 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 08:26:19 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 497, in get_scans_by_user
    decrypted_url = decrypt_sensitive_data(row[1])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 13:50:50 - login_window - DEBUG - Logger initialized successfully
2025-06-25 13:50:52 - login_window - DEBUG - Login UI components created.
2025-06-25 13:50:52 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 13:50:52 - login_window - INFO - LoginWindow initialized.
2025-06-25 13:51:02 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 13:51:02 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 497, in get_scans_by_user
    decrypted_url = decrypt_sensitive_data(row[1])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 13:51:37 - login_window - DEBUG - Logger initialized successfully
2025-06-25 13:51:38 - login_window - DEBUG - Login UI components created.
2025-06-25 13:51:38 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 13:51:38 - login_window - INFO - LoginWindow initialized.
2025-06-25 13:51:47 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 13:51:47 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 114, in _get_unverified_token_data
    data = base64.urlsafe_b64decode(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\Общий\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 497, in get_scans_by_user
    decrypted_url = decrypt_sensitive_data(row[1])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 116, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 13:53:01 - login_window - DEBUG - Logger initialized successfully
2025-06-25 13:53:02 - login_window - DEBUG - Login UI components created.
2025-06-25 13:53:02 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 13:53:02 - login_window - INFO - LoginWindow initialized.
2025-06-25 13:53:12 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 13:53:12 - login_window - ERROR - An error occurred during login: 
Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 131, in _verify_signature
    h.verify(data[-32:])
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 124, in login
    self.parent.go_to_dashboard(user_id, username)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 133, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 68, in __init__
    self.setup_ui()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 102, in setup_ui
    self.setup_reports_tab()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1452, in setup_reports_tab
    self.refresh_reports()
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 1464, in refresh_reports
    scans = get_scans_by_user(self.user_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\database.py", line 487, in get_scans_by_user
    result_data = decrypt_sensitive_data(row[2])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 275, in decrypt_sensitive_data
    return get_encryption().decrypt_data(encrypted_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\utils\encryption.py", line 153, in decrypt_data
    decrypted_bytes = self.fernet.decrypt(encrypted_bytes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 90, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 149, in _decrypt_data
    self._verify_signature(data)
  File "E:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\.venv\Lib\site-packages\cryptography\fernet.py", line 133, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken
2025-06-25 14:03:47 - login_window - DEBUG - Logger initialized successfully
2025-06-25 14:03:48 - login_window - DEBUG - Login UI components created.
2025-06-25 14:03:48 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 14:03:48 - login_window - INFO - LoginWindow initialized.
2025-06-25 14:04:10 - login_window - INFO - User Manokuz logged in successfully.
2025-06-25 18:44:38 - login_window - DEBUG - Login UI components created.
2025-06-25 18:44:38 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-25 18:44:38 - login_window - INFO - LoginWindow initialized.
2025-06-25 18:44:47 - login_window - INFO - User Manokuz logged in successfully.
2025-06-26 12:44:26 - login_window - DEBUG - Login UI components created.
2025-06-26 12:44:26 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-06-26 12:44:26 - login_window - INFO - LoginWindow initialized.
2025-06-26 12:44:36 - login_window - INFO - User Manokuz logged in successfully.
2025-07-01 13:37:36 - login_window - DEBUG - Login UI components created.
2025-07-01 13:37:36 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-07-01 13:37:36 - login_window - INFO - LoginWindow initialized.
2025-07-01 13:37:51 - login_window - INFO - User Manokuz logged in successfully.
2025-07-01 13:41:49 - login_window - DEBUG - Login UI components created.
2025-07-01 13:41:49 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-07-01 13:41:49 - login_window - INFO - LoginWindow initialized.
2025-07-01 13:41:58 - login_window - INFO - User Manokuz logged in successfully.
2025-07-28 17:49:01 - login_window - DEBUG - Login UI components created.
2025-07-28 17:49:01 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-07-28 17:49:01 - login_window - INFO - LoginWindow initialized.
2025-07-28 17:49:28 - login_window - WARNING - Failed login attempt for Manokuz: Неверное имя пользователя или пароль.
2025-07-28 18:14:06 - login_window - DEBUG - Login UI components created.
2025-07-28 18:14:06 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-07-28 18:14:06 - login_window - INFO - LoginWindow initialized.
2025-07-28 18:14:14 - login_window - INFO - User Manokuz logged in successfully.
2025-07-28 18:14:17 - login_window - ERROR - An error occurred during login: 'DashboardWindow' object has no attribute 'policy_combobox'
Traceback (most recent call last):
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\login_window.py", line 122, in login
    self.parent_window.go_to_dashboard(user_id, username)
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\ui\main_window.py", line 143, in go_to_dashboard
    self.dashboard_window = DashboardWindow(user_id, username, self)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 72, in __init__
    self.load_policies_to_combobox()
  File "e:\Python_Projects\Web_Scanner_SQL_XSS_CSRF\views\dashboard_window.py", line 774, in load_policies_to_combobox
    self.policy_combobox.clear()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DashboardWindow' object has no attribute 'policy_combobox'
2025-08-01 23:48:07 - login_window - DEBUG - Login UI components created.
2025-08-01 23:48:07 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-08-01 23:48:07 - login_window - INFO - LoginWindow initialized.
2025-08-01 23:48:17 - login_window - WARNING - Failed login attempt for Manokuz: Неверное имя пользователя или пароль.
2025-08-01 23:48:28 - login_window - INFO - User Manokuz logged in successfully.
2025-08-02 00:01:48 - login_window - DEBUG - Login UI components created.
2025-08-02 00:01:48 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-08-02 00:01:48 - login_window - INFO - LoginWindow initialized.
2025-08-02 00:02:07 - login_window - INFO - User Manokuz logged in successfully.
2025-08-06 21:45:40 - login_window - DEBUG - Login UI components created.
2025-08-06 21:45:40 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-08-06 21:45:40 - login_window - INFO - LoginWindow initialized.
2025-08-06 21:45:55 - login_window - INFO - User Manokuz logged in successfully.
2025-08-06 23:08:34 - login_window - DEBUG - Login UI components created.
2025-08-06 23:08:34 - login_window - INFO - Стили успешно загружены для окна авторизации
2025-08-06 23:08:34 - login_window - INFO - LoginWindow initialized.
2025-08-06 23:08:48 - login_window - INFO - User Manokuz logged in successfully.
